import { Badge, Card } from "@/components/shared/ui";
import { guardPage } from "@/server/auth/pageGuard";
import { requireUser } from "@/server/auth/session";
import { getOwnerAccessContext } from "@/server/modules/owner/access";
import { listOwnerSettlements } from "@/server/modules/tenantManagement/managementFee";
import { formatDate, formatNaira } from "@/lib/utils";

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const STATUS_TONE = { PENDING: "warning", APPROVED: "info", PROCESSING: "info", PAID: "success", FAILED: "danger", CANCELLED: "neutral" } as const;
const STATUS_LABEL = {
  PENDING: "Pending",
  APPROVED: "Approved",
  PROCESSING: "Processing",
  PAID: "Paid",
  FAILED: "Failed",
  CANCELLED: "Cancelled",
} as const;

const AWAITING = new Set(["PENDING", "APPROVED", "PROCESSING"]);

export default async function OwnerPayoutsPage() {
  const user = await guardPage(() => requireUser());
  const access = await getOwnerAccessContext(user.id);

  if (access.ownerId === null) {
    return (
      <div className="space-y-6">
        <h1 className="text-xl font-semibold">Payouts</h1>
        <Card>
          <p className="text-sm text-foreground-muted">Payouts appear here once your property manager generates a settlement for your rental portfolio.</p>
        </Card>
      </div>
    );
  }

  const settlements = await listOwnerSettlements(user, access.ownerId);
  const thisYear = new Date().getUTCFullYear();
  const paidThisYear = settlements
    .filter((s) => s.status === "PAID" && (s.settlementDate ?? s.periodEnd).getUTCFullYear() === thisYear)
    .reduce((sum, s) => sum + s.netAmountMinor, 0);
  const awaiting = settlements.filter((s) => AWAITING.has(s.status)).reduce((sum, s) => sum + s.netAmountMinor, 0);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Payouts</h1>
        <p className="mt-1 text-sm text-foreground-muted">
          What your property manager owes you each period, how it was worked out, and whether it has been paid. Nothing is deducted without being listed here.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <Card>
          <p className="text-xs text-foreground-muted">Paid in {thisYear}</p>
          <p className="mt-1 text-xl font-semibold text-success">{formatNaira(paidThisYear)}</p>
        </Card>
        <Card>
          <p className="text-xs text-foreground-muted">Awaiting payment</p>
          <p className="mt-1 text-xl font-semibold text-warning">{formatNaira(awaiting)}</p>
        </Card>
      </div>

      {settlements.length === 0 ? (
        <Card>
          <p className="font-medium">No payouts yet</p>
          <p className="mt-1 text-sm text-foreground-muted">Settlements generated by your property manager will be listed here.</p>
        </Card>
      ) : (
        <div className="space-y-3">
          {settlements.map((s) => (
            <Card key={s.id}>
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="font-medium">
                    {MONTH_NAMES[s.periodStart.getUTCMonth()]} {s.periodStart.getUTCFullYear()} · {s.property ? s.property.name : "All properties"}
                  </p>
                  <p className="mt-0.5 text-lg font-semibold">{formatNaira(s.netAmountMinor)}</p>
                </div>
                <Badge tone={STATUS_TONE[s.status]}>{STATUS_LABEL[s.status]}</Badge>
              </div>
              <dl className="mt-3 space-y-1 border-t border-border pt-3 text-sm">
                <Line label="Rent collected" value={formatNaira(s.grossCollectionsMinor)} />
                <Line label="Management fee" value={`− ${formatNaira(s.managementFeeMinor)}`} />
                <Line label="Maintenance & expenses" value={`− ${formatNaira(s.expensesMinor)}`} />
                {s.adjustmentsMinor !== 0 && <Line label="Adjustments" value={formatNaira(s.adjustmentsMinor)} />}
              </dl>
              {(s.settlementDate || s.paymentReference) && (
                <p className="mt-3 text-xs text-foreground-muted">
                  {s.settlementDate ? `Settled ${formatDate(s.settlementDate)}` : ""}
                  {s.settlementDate && s.paymentReference ? " · " : ""}
                  {s.paymentReference ? `Ref ${s.paymentReference}` : ""}
                </p>
              )}
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function Line({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <dt className="text-foreground-muted">{label}</dt>
      <dd>{value}</dd>
    </div>
  );
}
