export const AD_CATEGORY_OPTIONS: [string, string][] = [
  ["HOME_MAINTENANCE", "Home Maintenance"],
  ["CLEANING", "Cleaning"],
  ["MOVING_SERVICES", "Moving Services"],
  ["FURNITURE", "Furniture"],
  ["INTERIOR_DESIGN", "Interior Design"],
  ["INTERNET_PROVIDERS", "Internet Providers"],
  ["SOLAR_ENERGY", "Solar & Energy"],
  ["ELECTRICAL_SERVICES", "Electrical Services"],
  ["PLUMBING", "Plumbing"],
  ["AIR_CONDITIONING", "Air Conditioning"],
  ["PEST_CONTROL", "Pest Control"],
  ["SECURITY_SERVICES", "Security Services"],
  ["INSURANCE", "Insurance"],
  ["HOME_FINANCE", "Mortgage / Home Finance"],
  ["REAL_ESTATE", "Real Estate"],
  ["RESTAURANTS", "Restaurants"],
  ["FOOD_DELIVERY", "Food Delivery"],
  ["SUPERMARKETS", "Supermarkets"],
  ["LAUNDRY", "Laundry"],
  ["CAR_SERVICES", "Car Services"],
  ["HOME_APPLIANCES", "Home Appliances"],
  ["PROFESSIONAL_SERVICES", "Professional Services"],
  ["LOCAL_BUSINESSES", "Local Businesses"],
  ["ESTATE_VENDORS", "Estate Vendors"],
  ["OTHER", "Other"],
];

export const CAMPAIGN_GOAL_OPTIONS: [string, string][] = [
  ["WEBSITE_VISITS", "Website Visits"],
  ["CALL_BUSINESS", "Call Business"],
  ["WHATSAPP_BUSINESS", "WhatsApp Business"],
  ["REQUEST_QUOTE", "Request Quote"],
  ["BOOK_SERVICE", "Book Service"],
  ["VIEW_OFFER", "View Offer"],
  ["VISIT_STORE", "Visit Store"],
  ["LEAD_GENERATION", "Lead Generation"],
  ["PROPERTY_INQUIRY", "Property Inquiry"],
];
