import type { MetadataRoute } from "next";
import { BRAND } from "@/lib/brand";

/**
 * Makes the Resident App installable as a PWA. Icons reuse the existing
 * brand asset (public/logo-icon.png) rather than fabricating new sizes —
 * a proper 192x192/512x512 maskable icon set should be generated by
 * design before this ships broadly, but the existing asset is enough for
 * a working install prompt today.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${BRAND.name} Resident App`,
    short_name: BRAND.name,
    description: "Your estate, right in your pocket — visitors, payments, maintenance and community updates.",
    start_url: "/",
    display: "standalone",
    background_color: "#f7f7f7",
    theme_color: "#1a1a1a",
    icons: [
      {
        src: "/logo-icon.png",
        sizes: "300x313",
        type: "image/png",
      },
    ],
  };
}
